name: Reusable Build and Deploy Workflow for Backend

on:
  workflow_call:
    inputs:
      docker-image-name:
        required: true
        type: string
      docker-port:
        required: true
        type: string
    secrets:
      docker-username:
        required: true
      docker-password:
        required: true
      ec2-host:
        required: true
      ec2-user:
        required: true
      ec2-ssh-key:
        required: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      - name: Build with Gradle
        run: ./gradlew clean build -x test

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.docker-username }}
          password: ${{ secrets.docker-password }}

      - name: Docker Build and Push
        run: |
          docker build -t ${{ secrets.docker-username }}/${{ inputs.docker-image-name }} .
          docker push ${{ secrets.docker-username }}/${{ inputs.docker-image-name }}

      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.3
        with:
          host: ${{ secrets.ec2-host }}
          username: ${{ secrets.ec2-user }}
          key: ${{ secrets.ec2-ssh-key }}
          script: |
            docker rm -f ${{ inputs.docker-image-name }} || true
            docker rmi ${{ secrets.docker-username }}/${{ inputs.docker-image-name }} || true
            docker pull ${{ secrets.docker-username }}/${{ inputs.docker-image-name }}
            docker run -d --name ${{ inputs.docker-image-name }} -p ${{ inputs.docker-port }}:8080 \
              -e SPRING_PROFILES_ACTIVE=prod \
              ${{ secrets.docker-username }}/${{ inputs.docker-image-name }}
